#!/bin/bash
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

UBUNTU="Ubuntu"
checkDistro() {
    distroName=$(grep -Po '^NAME="\K.*(?=")' /etc/os-release)

    if [ "$distroName" != "$UBUNTU" ]; then
        return 1
    fi
}

# don't put lines starting with space and duplicate lines in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth:erasedups

# append to the history file, don't overwrite it
shopt -s histappend

# add date to history
HISTTIMEFORMAT="%F %T: "

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=100000
HISTFILESIZE=100000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

if checkDistro "$UBUNTU"; then

    # enable programmable completion features (you don't need to enable
    # this, if it's already enabled in /etc/bash.bashrc and /etc/profile
    # sources /etc/bash.bashrc).
    if ! shopt -oq posix; then
      if [ -f /usr/share/bash-completion/bash_completion ]; then
        # shellcheck source=/dev/null
        . /usr/share/bash-completion/bash_completion
      elif [ -f /etc/bash_completion ]; then
        # shellcheck source=/dev/null
        . /etc/bash_completion
      fi
    fi

    complete -C /usr/bin/terraform terraform
fi

sourceAliases() {
    local file=$1
    if [ -f "$file" ]; then
    # shellcheck source=/dev/null
        source "$file"
    fi
}

sourceAliases "$HOME/.bash_aliases"
# Aliases that are not part of dotfiles
sourceAliases "$HOME/.bash_aliases_local"


export GBT_CARS='Status, Os, Hostname, Dir, Kubectl, Git, Sign'
export GBT_CAR_KUBECTL_FORMAT=' {{ Icon }} {{ Context }}/{{ Namespace }}'
PS1='$(gbt $?)'
