#!/bin/bash
# ~/.bash_aliases
#

_serve-http() {
	local endpoint="127.0.0.1:8080"
	if [[ $1 =~ ^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.*:[0-9]{2,5}$ ]]; then
	# if [[ $1 =~ .:[0-9]{2,5}$ ]]; then
		endpoint="$1"
	fi
	if podman run --rm --name serve-http -v "$(pwd)":/usr/share/nginx/html -p "$endpoint":80 -d nginx:alpine; then
		echo "Nginx listening at $endpoint"
	fi
}

_wg-wrapper() {
	local action="$1"
	local conf="$2"
	set -x;
	trap 'set +x' RETURN SIGINT SIGABRT

	sudo wg-quick "$action" "$HOME/Documents/Wireguard/wg.$conf.conf"
}

alias drop-history-from-current-shell='unset HISTFILE'
alias grep='grep --color=auto'
alias k='kubectl'
alias ls='ls --color=auto'
alias qrencode='qrencode -t ansiutf8'
alias serve-http='_serve-http'
alias start-wg='_wg-wrapper up'
alias stop-wg='_wg-wrapper down'
alias vi='vim'


# load kubectl completions
_completion_loader kubectl

# assign kubectl's completion function _start_kubectl to k
complete -o default -F __start_kubectl k
