# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Don't insert a blank line between shell prompts
add_newline = false

# use custom format so most of modules will stay disabled (especially those related to languages)
format = """
$os\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$aws\
$gcloud\
$cmd_duration\
$line_break\
$jobs\
$battery\
$character\
"""

[directory]
truncation_length = 2

[git_branch]
truncation_length = 32

[kubernetes]
disabled = false
format ="[$symbol$context( \\($namespace\\))]($style)|"
style = "blue bold"

[hostname]
ssh_only = false
format = "[$ssh_symbol$hostname]($style)|"

[os]
disabled = false

[os.symbols]
Arch = " "
Ubuntu = " "
